
@baseUrl = http://localhost:5000
@urlPath = api/v1

###

# FOLLOW a User

PUT {{baseUrl}}/{{urlPath}}/user/follow/6461f3c3d29458b8bdad018c
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###

# UNFOLLOW a User

PUT {{baseUrl}}/{{urlPath}}/user/unFollow/6461f3abd29458b8bdad0185/6461f0afd29458b8bdad016b
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###

# GET USER FOLLOWING

GET {{baseUrl}}/{{urlPath}}/user/following
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###

# GET USER FOLLOWING

GET {{baseUrl}}/{{urlPath}}/user/followers/6461f3c3d29458b8bdad018c
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###

# GET USER FOLLOWING

GET {{baseUrl}}/{{urlPath}}/user/following
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###

# BLOCK a User

PUT {{baseUrl}}/{{urlPath}}/user/block/461f0f6d29458b8bdad0176
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###

# UNBLOCK a User

PUT {{baseUrl}}/{{urlPath}}/user/unblock/
Content-Type: application/json
Accept: application/json
withCredentials: true

{}
