
@baseUrl = http://localhost:5000
@urlPath = api/v1

###

PUT {{baseUrl}}/{{urlPath}}/user/follow/6461f3abd29458b8bdad0185
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###

PUT {{baseUrl}}/{{urlPath}}/user/unFollow/6461f3abd29458b8bdad0185/6461f0afd29458b8bdad016b
Content-Type: application/json
Accept: application/json
withCredentials: true

{}
