@baseUrl = http://localhost:5000
@urlPath = api/v1

###

# CREATE a REACTION
POST {{baseUrl}}/{{urlPath}}/post/reaction
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "6452791abcfe3f92b5e1084d",
  "postId": "645a18f5167de8034fb62a82",
  "type": "happy",
  "previousReaction": "",
  "postReactions": {"like": 0,"love": 0,"happy": 1,"sad": 0,"wow": 0,"angry": 0},
  "profilePicture": "https://res.cloudinary.com/dh7gwd3a2/image/upload/v1683126554/6452791abcfe3f92b5e1084d"
}

###

# DELETE a REACTION
DELETE {{baseUrl}}/{{urlPath}}/post/reaction/645a18f5167de8034fb62a82/angry/{"like":0,"love":0,"happy":0,"sad":0,"wow":0,"angry":0}
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###

# GET REACTIONS
GET {{baseUrl}}/{{urlPath}}/post/reactions/645a18f5167de8034fb62a82
Content-Type: application/json
Accept: application/json
withCredentials: true

###

# GET SINGLE REACTION by USER
GET {{baseUrl}}/{{urlPath}}/post/single/reaction/username/Laurent/645a18f5167de8034fb62a82
Content-Type: application/json
Accept: application/json
withCredentials: true

###

# GET ALL REACTIONS OF a USER
GET {{baseUrl}}/{{urlPath}}/post/reactions/username/Laurent
Content-Type: application/json
Accept: application/json
withCredentials: true
